### ISSUE TITLE
Mistake in prep_data.py

### ISSUE THREAD

**Issue by xcfcode** [Alex-Fabbri/Multi-News#1]
Nice Job!!!
https://github.com/Alex-Fabbri/Multi-News/blob/eb9ae197fcf94c17188e261cce84332882b49d98/data/scripts/prep_data.py#L71
Maybe it should be `f"../final_data/{split}.tgt.txt", "w"`

**Comment by Alex-Fabbri** [comment]
Thanks for pointing that out! I updated the code.
