### ISSUE TITLE
models for PG and Hi-MAP.

### ISSUE THREAD

**Issue by yashkumaratri** [Alex-Fabbri/Multi-News#12]
Hi,

Can you provide your models for pointer generator and HI-Map.

**Comment by Alex-Fabbri** [comment]
Please see [this link](https://drive.google.com/open?id=1yfJGKjzCi4LJyKs9u48DmIdlVdxnngbb).

**Comment by yashkumaratri** [comment]
Hey Alex, 
I need the model for custom predictions, cause training will require hardware. Which I currently don't have.

**Comment by Alex-Fabbri** [comment]
I pasted the wrong link about -- sorry about that. Here is the link to the pretrained models: 
https://drive.google.com/drive/folders/1h2xuCZXy4gev1KmsRjmBoDcSJYa5bJ4Q
