### ISSUE TITLE
Code for data analysis

### ISSUE THREAD

**Issue by MehwishFatimah** [Alex-Fabbri/Multi-News#15]
Hi Alex,

I read your paper and it is very interesting. 
I am interested in analysis part, but couldn't find that code in this repo.
May you please provide analysis code as well.
Many thanks!

**Comment by Alex-Fabbri** [comment]
Thanks for your interest in the paper! I just added some scripts [here](https://github.com/Alex-Fabbri/Multi-News/tree/master/data/scripts). The paths will need to be modified, but basically everything should be there. Please let me know if something's missing.

**Comment by MehwishFatimah** [comment]
Thank you :)
