### ISSUE TITLE
OpenMNT-baseline, multi-GPU

### ISSUE THREAD

**Issue by GPUHunter** [Alex-Fabbri/Multi-News#16]
Dear Alex

I am your big fan! I am playing around your transformer baseline (OpenNMT), but found that the multi-GPU is not implemented. Do you think if I replace the `onmt` module, things will work?

**Comment by Alex-Fabbri** [comment]
Thanks! You should be able to make use of multiple GPUs by following [these instructions](http://opennmt.net/OpenNMT-py/FAQ.html#do-you-support-multi-gpu) and changing the training script. Let me know if you encounter any problems.

**Comment by GPUHunter** [comment]
Thanks Alex, also I am wondering for your provided trained model here, `https://drive.google.com/drive/folders/15nUeJdLtkzaVsVG9dOW8F_6ArGb-Zdpw`, do you know what training script you use? I am trying to reproduce the result and found out that the transformer that I trained from the `truncated_processed` data and exact parameter from your training script `https://github.com/Alex-Fabbri/Multi-News/blob/master/code/OpenNMT-py-baselines/run_train_transformer.sh` give different output during inference as comparing to your provided trained model, do you know what is going on?

**Comment by Alex-Fabbri** [comment]
The training script you linked to is the one we used. What kind of results are you getting? Also if you could provide more info about your environment, e.g. which PyTorch version, that may be causing the difference.

**Comment by Alex-Fabbri** [comment]
Going to close this for now. Please reopen if you have any additional questions or updates!
