### ISSUE TITLE
Trained Model for HI_MAP

### ISSUE THREAD

**Issue by apekshapriya** [Alex-Fabbri/Multi-News#17]
Hey Alex,
Really appreciate the work you have done! 
There was one request, I have tried the three models that you have shared. Can you share the trained model for HI_Map as well?

**Comment by Alex-Fabbri** [comment]
The model is found under newser_mmr [here](https://drive.google.com/drive/folders/1h2xuCZXy4gev1KmsRjmBoDcSJYa5bJ4Q?usp=sharing).
