### ISSUE TITLE
Can not get the whole dataset

### ISSUE THREAD

**Issue by xcfcode** [Alex-Fabbri/Multi-News#2]
Hi, Alex, After trying many times, I finally get `train/dev/test 44824/5601/5604` which is different from the number described in the paper, and I recorded the URLs which can not be successfully crawled. Could you please help me?

**Comment by Alex-Fabbri** [comment]
Sure! Can you send me the URLs which cannot be crawled? Either here or via email @ alexander.fabbri@yale.edu

**Comment by xcfcode** [comment]
Sincerely Thanks!
