### ISSUE TITLE
Can not reproduce Output with pretrained Hi_MAP model

### ISSUE THREAD

**Issue by christophhaushofer** [Alex-Fabbri/Multi-News#23]
Hi Alex,

I´m trying to reproduce the published [output ](https://drive.google.com/drive/folders/1yfJGKjzCi4LJyKs9u48DmIdlVdxnngbb ) with your [pretrained hi_map model](https://drive.google.com/drive/folders/1h2xuCZXy4gev1KmsRjmBoDcSJYa5bJ4Q) . I use the cleaned, tokenized and truncated test src data file [you provided](https://drive.google.com/drive/folders/1qqSnxiaNVEctgiz2g-Wd3a9kwWuwMA07).

The command I use for running the model is: (as described in the readme and the run_inference_newser.sh)

`python translate.py -gpu 0 -batch_size 8 -beam_size 4 -model pretrained_models/newser_mmr/Feb17__step_20000.pt -src data/multi-news/test.txt.src.tokenized.fixed.cleaned.final.truncated.txt -output output/Feb17__step_20000_full.output -min_length 200 -max_length 300 -verbose -stepwise_penalty -coverage_penalty summary -beta 5 -length_penalty wu -alpha 0.9 -verbose -block_ngram_repeat 3 -ignore_when_blocking "story_separator_special_tag" `

in the terminal.

Althought I managed to get the model up an running on my Windows machine (Windows 10 Home, Torch 1.4.0, Python 3.7.3), I´m not able to reproduce your output. 

Here is an example for my output from the model for the first two documents in the test.txt.src.tokenized.fixed.cleaned.final.truncated file:

`– it ' s a new day , but that ' s what we ' re not to be a lot of your life . as for the first time , you ' re going to see it out , but they ' re now not to have a lot to do so , the new york times reports . " i ’ ve been a lot of <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank>`
`– if you ' re a <unk> , it ' s a good thing , but that ' s what they ' re saying : " i ' ve seen it , " the new york times reports . " i can ' t believe . " as for the <unk> , they ' ll be able to be a " <unk> , " but it was " one of the most time , " he writes , adding that it was a " one woman . " but , " this is one of those who ' ve been able to do it . " the washington post reports that the " <unk> " is a <unk> to the <unk> <unk> : " it ’ s a very way to see a <unk> <unk> <unk> , but it ’ ll be a good time for it , but i don ’ t want it . i don ' t know if it was . i ' m going to do . " the <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank> <blank>`

My torch versions are:
`torch==1.4.0
torchtext==0.5.1
torchvision==0.5.0`

I'd really appreciate it if you could help me out here. Thank you!

**Comment by Alex-Fabbri** [comment]
I just updated the code to a point which will reproduce the results. The change was an attempted bug fix but which needs to be checked further first. I will update the repo as I have an update.

**Comment by christophhaushofer** [comment]
Thanks Alex! Now it works just as expected.
Cheers
