### ISSUE TITLE
how to Separate Doc in "Preprocessed, but not truncated, data" 

### ISSUE THREAD

**Issue by yeliu918** [Alex-Fabbri/Multi-News#25]
Hi, 

How to get the different doc in "Preprocessed, but not truncated, data"? I didn't see specific token and I try "\n", but the text doesn't have any.

**Comment by elainespak** [comment]
I believe `" story_separator_special_tag "` is the separator you're looking for. Same goes for the "preprocessed, truncated, data."

**Comment by Alex-Fabbri** [comment]
Yes, @elainespak is correct; please reopen the issue if you have any other questions!

**Comment by bnaman50** [comment]
Hey @Alex-Fabbri , 

I think there is slight discrepancy in the data provided on the google drive and the data generated by the scripts. 
I wanted to understand the code. Thus, I ran the scripts for just one sample (`id=136951`). 

This is how the source and target output looks like by your `prep_data.py` file (call it `Case I`) - 

_Source -_
```
Iran is planning new military exercises near the strategic Strait of Hormuz , according to a naval commander , after threatening to close the strait and completing another set of maneuvers. In this picture ... 
```
(truncated for brevity)

_Target -_
```
– western officials are fairly sanguine that iran ' s recent provocations are only posturing . but on the streets of tehran , sanctions are taking a real toll , and the populace expects violence , the washington post reports . the country is in the midst of a currency crisis that has made prices shoot up on everything from iphones to crucial medicine — when either can be found at all . " i will tell you what this is leading to : war , " says one merchant . " my family , friends and i — we are all desperate . " iran certainly isn ' t doing anything to assuage those fears ; late yesterday its semi-official news agency announced that it would conduct another round of military exercises near the strait of hormuz next month . a naval commander says these war games will be " different " than the attention-grabbing 10-day drill iran ' s navy just completed , without specifying how , according to the ap . click for more on iran ' s recent internet crackdown .
```

whereas this is what is there on [Google Drive](https://drive.google.com/drive/folders/1qZ3zJBv0zrUy4HVWxnx33IsrHGimXLPy), `val.txt.src` file (call it `Case II`)- 

_Source -_ 
```
iran is planning new military exercises near the strategic strait of hormuz , according to a naval commander , after threatening to close the strait and completing another set of maneuvers .     in this picture ...
``` 
(truncated for brevity)

 _Target -_ 
```
( Newser ) – Western officials are fairly sanguine that Iran ' s recent provocations are only posturing. But on the streets of Tehran , sanctions are taking a real toll , and the populace expects violence , the Washington Post reports. The country is in the midst of a currency crisis that has made prices shoot up on everything from iPhones to crucial medicine — when either can be found at all. " I will tell you what this is leading to : war , " says one merchant. " My family , friends and I — we are all desperate. " Iran certainly isn ' t doing anything to assuage those fears ; late yesterday its semi-official news agency announced that it would conduct another round of military exercises near the Strait of Hormuz next month. A naval commander says these war games will be " different " than the attention-grabbing 10-day drill Iran ' s Navy just completed , without specifying how , according to the AP. Click for more on Iran ' s recent Internet crackdown.
```

I see the following differences - 
1. Text is lowercased in `Case II` but not in `Case I`.
2. I think you there is a paragraph separator (large space) in `Case II` but not in `Case I` i.e. observe the space after `another set of maneuvers .` phrase in `Case I` vs `Case II`. 
3. The target file also has similar issues with initial `-` and `Newser` is also removed.

I am using someone else's [project](https://github.com/PaddlePaddle/Research/tree/master/NLP/ACL2020-GraphSum) which makes use of your processed dataset. My goal is to fine-tune their model on my own dataset. Thus, I just want to make sure I am doing the pre-processing correctly. 

Could you please help me figure this out? **This paragraph separator thing is really important for their model if I understand correctly.**

Thanks, 
Naman
