### ISSUE TITLE
data change?

### ISSUE THREAD

**Issue by bultiful** [Alex-Fabbri/Multi-News#29]
hi , Alex ! thank u very much  @Alex-Fabbri
I have a question to ask you : If transformer models are trained in other languages, such as Chinese .Can Chinese data be preprocessed directly according to your method ?（Use directly OpenNMT baselines "run_preprocess.sh"）

**Comment by Alex-Fabbri** [comment]
Hi, 
Yes you should be able to run OpenNMT on Chinese data without a problem. Here's a [tutorial](https://towardsdatascience.com/building-a-translation-system-in-minutes-d82a154f603e) I found quickly which uses OpenNMT with Chinese.

**Comment by bultiful** [comment]
Thank you very much for your reply ！I'll try it on your suggestion.&nbsp;




---Original---

**Comment by bultiful** [comment]
hi , Alex !   @Alex-Fabbri 
I don't know much about the paper, so I'd like to consult you .
In your paper：“We simply introduce a special token between source documents to aid our models in detecting document-to-document relationships and leave direct modeling of this relationship, as well as modeling longer input sequences, to future work.” **How to detect the relationship between documents with special tags? How does the code model this relationship?**

**Comment by Alex-Fabbri** [comment]
Hi @bultiful, for this we just insert a special token between documents which doesn't appear anywhere else in the text in hopes that the model learns that this separates documents containing different information. The hierarchical part is applied on sentences and not documents.
