### ISSUE TITLE
Dataset in original formats & evaluation

### ISSUE THREAD

**Issue by jiacheng-xu** [Alex-Fabbri/Multi-News#4]
Hi Alex,
    I am trying to use this dataset which seems pretty high quality. Do you consider to distribute another version of dataset via Google Drive **before tokenization and lower casing**? 
    I want to do some preprocessing with the dataset but the files in Google drive ([train/dev/test].txt.[src/tgt]) are already lowercased the tokenized which might hurt the performance of downstream tools like StanfordNLP, entity linking tools, etc. 

And also for fair comparison in evaluation, shall we use the tokenized version or do detokenization before feeding to ROUGE (will this affect the ROUGE score somehow?) example: 
> kavanaugh didn ' t state

where "didn ' t" are treated as three words (a little overly fine-grained). Did you use the tokenized version of the reference summary to get the number from your paper?

**Comment by Alex-Fabbri** [comment]
Hi Jiacheng, 

Thanks for your interest! I just uploaded the [original dataset](https://drive.google.com/open?id=1qZ3zJBv0zrUy4HVWxnx33IsrHGimXLPy) before tokenization and lower casing. Yes, the numbers from the paper use the tokenized version, although we are going to upload numbers without it as well.

**Comment by jiacheng-xu** [comment]
Thanks Alex.
