### ISSUE TITLE
How many GPUs are needed?

### ISSUE THREAD

**Issue by Vincent-Li-9701** [Alex-Fabbri/Multi-News#6]
Hi Alex,

Thank you for the code and data. I was trying to reproduce the results in the paper. However, I keep running into out of memory issue. How many GPUs did you use during your experiments? 

Thank you

**Comment by Alex-Fabbri** [comment]
Just to make sure, did you run the script to truncate the input size as in the paper? This was added to the prep_data.py script. We just used a single K80 with gradient accumulation (see scripts, e.g. this one), although making use of OpenNMT's multi-gpu training would be useful.

**Comment by Alex-Fabbri** [comment]
OOM from input not being tokenized. See [thread](https://github.com/Alex-Fabbri/Multi-News/issues/3#issuecomment-529822330) for additional details. Closing for now. Feel free to reopen.
