### ISSUE TITLE
About input file upload

### ISSUE THREAD

**Issue by zhongxia199603** [Alex-Fabbri/Multi-News#7]
Can you upload this processed file /home/lily/af726/spring-2019/summarization_general/data-final/data-truncated-opennmt/train.txt.src.tokenizd.fixed.cleaned.truncated .etc
This file was used in the inputs, but was not found in the released dataset.

**Comment by Alex-Fabbri** [comment]
Sorry for the late reply. That corresponds to the preprocessed and truncated input which you can get from taking the processed input and applying the [truncate function](https://github.com/Alex-Fabbri/Multi-News/blob/master/data/scripts/prep_data.py#L106). For convenience, I uploaded that [here](https://drive.google.com/drive/folders/1qqSnxiaNVEctgiz2g-Wd3a9kwWuwMA07?usp=sharing) as well.

**Comment by Alex-Fabbri** [comment]
Please open if you have any additional questions.
